### ISSUE TITLE
Bug with multiple menus

### ISSUE THREAD

**Issue by edgarsss** [arifwidip/mobilemenu#9]
There is a bug if you use multiple menus!

If I set up for example to menus

<code>$('ul.sf-menu').mobileMenu();
$('ul.top-menu-nav').mobileMenu();
</code>

Then the <code>.sf-menu</code> menus select contains also <code>.top-menu-nav</code> content

 <code>.sf-menu</code> menu
![untitled](https://f.cloud.github.com/assets/5087396/854283/97d0b906-f4fe-11e2-99de-fc640124ffda.png)

<code>.top-menu-nav</code> menu 

![untitled](https://f.cloud.github.com/assets/5087396/854272/45a8b700-f4fe-11e2-89a4-2b80b39b69e6.png)

Is there a fix for this?

**Comment by arifwidip** [comment]
Ok i have fixed this bug.
